name: Resume CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Date Variables (Month and Year)
      - name: Set date variables
        id: date_vars
        run: |
          MONTH=$(date +%b | tr '[:upper:]' '[:lower:]')
          YEAR=$(date +%Y)
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "YEAR=$YEAR" >> $GITHUB_ENV

      # Step 3: Set Up Miniconda and Install Mamba
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: 3.9
          channels: conda-forge

      - name: Install Mamba
        run: |
          conda install -y -c conda-forge mamba

      # Step 4: Install LaTeX Packages via Mamba
      - name: Install LaTeX packages with Mamba
        run: |
          mamba install -y -c conda-forge texlive-core texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk

      # Step 5: Compile LaTeX Files into PDF
      - name: Compile LaTeX
        run: |
          cd resume
          latexmk -pdf resume.tex

      # Step 6: Rename the Generated PDF
      - name: Rename PDF
        run: |
          cd resume
          # Find the latest PDF generated by latexmk
          PDF_FILE=$(ls -t *.pdf | head -n1)
          NEW_PDF="resume-mabuelanin-${{ env.MONTH }}-${{ env.YEAR }}.pdf"
          echo "Renaming $PDF_FILE to $NEW_PDF"
          mv "$PDF_FILE" "$NEW_PDF"
      
      # Step 7: Upload PDF as workflow artifact (happens on every push)
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: resume/resume-mabuelanin-${{ env.MONTH }}-${{ env.YEAR }}.pdf
          retention-days: 30

  release:
    # This job runs only if the commit message is exactly "make-a-release"
    if: github.event.head_commit.message == 'make-a-release'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants permission to create releases and upload artifacts

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Set Date Variables (Month and Year)
      - name: Set date variables
        id: date_vars
        run: |
          MONTH=$(date +%b | tr '[:upper:]' '[:lower:]')
          YEAR=$(date +%Y)
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "YEAR=$YEAR" >> $GITHUB_ENV
          
      # Step 3: Download the PDF artifact from the build job
      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: resume-pdf
          path: resume/

      # Step 4: Package LaTeX Source Files into ZIP
      - name: Package source files
        run: |
          cd resume
          zip -r source-code.zip resume.tex src/

      # Step 5: Create GitHub Release with Attached Assets
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "resume-${{ env.MONTH }}-${{ env.YEAR }}"
          name: "Resume Release ${{ env.MONTH }}-${{ env.YEAR }}"
          body: |
            Automated release of resume for ${{ env.MONTH }} ${{ env.YEAR }}.
          artifacts: "resume/resume-mabuelanin-${{ env.MONTH }}-${{ env.YEAR }}.pdf,resume/source-code.zip"
