name: Make a Release

on:
  push:
    branches:
      - master

jobs:
  release:
    # This job runs only if the commit message is exactly "make-a-release"
    if: github.event.head_commit.message == 'make-a-release'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants permission to create releases and upload artifacts

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set Date Variables (Month and Year)
      - name: Set date variables
        id: date_vars
        run: |
          MONTH=$(date +%b | tr '[:upper:]' '[:lower:]')
          YEAR=$(date +%Y)
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "YEAR=$YEAR" >> $GITHUB_ENV

      # Step 3: Set Up Conda with Mamba
      - name: Set up Conda with Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: 3.9
          mamba-version: "latest"

      # Step 4: Install LaTeX Packages via Mamba
      - name: Install LaTeX packages with Mamba
        run: |
          mamba install -y -c conda-forge texlive-core texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk

      # Optional Debugging Step: List Files After Installation
      - name: List LaTeX Installation
        run: |
          which latexmk
          latexmk -version

      # Step 5: Compile LaTeX Files into PDF
      - name: Compile LaTeX
        run: |
          cd resume
          latexmk -pdf resume.tex

      # Optional Debugging Step: List Files After Compilation
      - name: List Files After Compilation
        run: |
          cd resume
          ls -la

      # Step 6: Rename the Generated PDF
      - name: Rename PDF
        run: |
          cd resume
          # Find the latest PDF generated by latexmk
          PDF_FILE=$(ls -t *.pdf | head -n1)
          echo "Renaming $PDF_FILE to resume-mabuelanin-${MONTH}-${YEAR}.pdf"
          mv "$PDF_FILE" "resume-mabuelanin-${MONTH}-${YEAR}.pdf"

      # Optional Debugging Step: Verify Renamed PDF
      - name: Verify Renamed PDF
        run: |
          cd resume
          ls -la

      # Step 7: Package LaTeX Source Files into ZIP
      - name: Package source files
        run: |
          cd resume
          zip -r source-code.zip resume.tex src/

      # Optional Debugging Step: Verify ZIP File
      - name: Verify ZIP File
        run: |
          cd resume
          ls -la

      # Step 8: Create GitHub Release with Attached Assets
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "resume-${{ env.MONTH }}-${{ env.YEAR }}"
          name: "Resume Release ${{ env.MONTH }}-${{ env.YEAR }}"
          body: |
            Automated release of resume for ${{ env.MONTH }} ${{
            env.YEAR }}.
          artifacts: "resume/resume-mabuelanin-${{ env.MONTH }}-${{ env.YEAR }}.pdf,resume/source-code.zip"
